CREATE TABLE Buy_Records(
    id INT NOT NULL AUTO_INCREMENT,
    userId VARCHAR(32) NOT NULL,
    share DECIMAL(10,2) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    total DECIMAL(10,2) NOT NULL,
    company VARCHAR(16) NOT NULL,
    open_time DATETIME,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);