CREATE TABLE Sell_Records(
    id INT NOT NULL AUTO_INCREMENT,
    userId VARCHAR(32) NOT NULL,
    share DECIMAL(10,2),
    price DECIMAL(10,2),
    porfit DECIMAL(10,2),
    total DECIMAL(10,2),
    company VARCHAR(16) NOT NULL,
    close_time DATETIME,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);