version: '3.8'

services:
  app:
    build: .
    ports:
      - "1233:1234"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data

volumes:
  redis-data: 