CREATE TABLE TechNews(
    id INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL UNIQUE,
    release_time VARCHAR(128),
    publisher VARCHAR(128),
    web_url VARCHAR(512),
    PRIMARY KEY (id),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);