CREATE TABLE Users(
    id INT NOT NULL AUTO_INCREMENT,
    userId  VARCHAR(32) NOT NULL,
    md5_userId VARCHAR(64) NOT NULL,
    pwd VARCHAR(64) NOT NULL,
    salt VARCHAR(32) NOT NULL,
    PRIMARY KEY (id),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);