CREATE TABLE Statements(
    id INT NOT NULL AUTO_INCREMENT,
    Market_Cap VARCHAR(16),
    Income VARCHAR(16),
    Sales VARCHAR(16),
    Book_sh VARCHAR(128),
    Cash_sh VARCHAR(16),
    Dividend VARCHAR(16),
    Dividend_percent VARCHAR(16),
    Employees VARCHAR(16),
    Recom VARCHAR(16),
    PE VARCHAR(16),
    Forward_PE VARCHAR(16),
    PEG VARCHAR(16),
    PS VARCHAR(16),
    PB VARCHAR(16),
    PC VARCHAR(16),
    PFCF VARCHAR(16),
    Quick_Ratio VARCHAR(16),
    Current_Ratio VARCHAR(16),
    DebtEq VARCHAR(16),
    LT_DebtEq VARCHAR(16),
    EPS_ttm VARCHAR(16),
    EPS_next_Y VARCHAR(16),
    EPS_next_Q  VARCHAR(16),
    EPS_this_Y VARCHAR(16),
    EPS_grow_next_Y VARCHAR(16),
    EPS_next_5Y VARCHAR(16),
    EPS_past_5Y VARCHAR(16),
    Sales_past_5Y VARCHAR(16),
    Sales_QQ VARCHAR(16),
    EPS_QQ VARCHAR(16),
    Insider_Own VARCHAR(16),
    Insider_Trans VARCHAR(16),
    Inst_Own VARCHAR(16),
    Inst_Trans VARCHAR(16),
    ROA VARCHAR(16),
    ROE VARCHAR(16),
    ROI VARCHAR(16),
    Gross_Margin VARCHAR(16),
    Oper_Margin VARCHAR(16),
    Profit_Margin VARCHAR(16),
    Payout VARCHAR(16),
    Shs_Outstand VARCHAR(16),
    Shs_Float VARCHAR(16),
    Short_Ratio VARCHAR(16),
    Target_Price VARCHAR(16),
    RSI_14 VARCHAR(16),
    Rel_Volume VARCHAR(16),
    Avg_Volume VARCHAR(16),
    Volume VARCHAR(16),
    Beta VARCHAR(16),
    ATR VARCHAR(16),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    company VARCHAR(16),
    PRIMARY KEY (id)
);